### ISSUE TITLE
Advanced Generators integration?

### ISSUE THREAD

**Issue by popps73x** [GrimCo/CoopLife2#11]
Bio Coal from AA does not currently have a Carbon Value.  (s/b 800?)  so you would not be able to use it in a syngas producer to create fuel for the generator.  minor issue.

**Comment by XEridaniTribalX** [comment]
I'm working on getting this set up.

**Comment by XEridaniTribalX** [comment]
As of PR #20, (the PR pulled the files early for some reason before I was done. Silly GitHub. xD), the AA Bio Coal has been added to the Syngas Producer, and the AA canola oils have been added to the Gas Turbine.
