### ISSUE TITLE
Morphing causes Auto-Walking (0.4)

### ISSUE THREAD

**Issue by FoxBotGames** [GrimCo/CoopLife2#14]
Happens in both SP and MP
Changing Forge Version does Nothing to Help
Movement goes: SE for Chickens, NW for Sheep
Server Reported a Resource Leak
Not any of the new Mods
Perhaps a different Mod updated and is causing issues?

**Comment by FoxBotGames** [comment]
Tropicraft Causing Issue

**Comment by Vaygrim** [comment]
As we've dropped Advanced Rocketry, we've got no actual REASON to use Tropicraft anymore.

Oh also.. the mod devs don't seem to want to fix this bug. (shrug)
