### ISSUE TITLE
Obsidian Tools Recipe Overlap

### ISSUE THREAD

**Issue by FoxBotGames** [GrimCo/CoopLife2#15]
Croparia Obsidian Tools and Actually Additions Obsidian Tools Recipes conflict, AA Tools get prioritised over Croparia Tools
Croparia Obsidian Tools are used in end game tool (elemental tools) 

Suggest adding AA Obsidian Tools as another Tool to use for the Elemental Tools from Croparia
OR Remove/Disable AA Obsidian Tools as they are not used as much as the ones from Croparia as well as AA Tools have a remarkably low EMC value (Even the AIOTs are low for such a high utility item)

**Comment by Vaygrim** [comment]
Disabled Obsidian tools and armor (full set) in AA.
