### ISSUE TITLE
Chicken Shades

### ISSUE THREAD

**Issue by FoxBotGames** [GrimCo/CoopLife2#18]
Old CL1 patreon skins are ready! Let me know whenever we what to add them in!

Skins for:
Vaygrim, Fox, Morvy, Preacher, Cutts, DragonRacer73, Ferg (cat), Gabbroccia, Gyvavaizdis, Mahldcat, NecromancerKing, Ralnick, Romanticistpoet, Saphrym, BigWayne2234, Barlock (And Angry Barlock), Craig, and Veggestoss.

Any suggestions of skins we dont want?

**Comment by FoxBotGames** [comment]
Drop:
NecromancerKing (Not Patreon Anymore) and Romanticistpoet (Left Community)

**Comment by FoxBotGames** [comment]
I found an Eridani skin!
(definetly didnt forget or anything, nope definetly not that)

**Comment by FoxBotGames** [comment]
Do we want to get some newish Patreon (Twtich Supporters too?) skins? I think I can handle making them so long as I get their minecraft skin or their input on a design idea. Regardless of how little I use a pixel based art creator.... Or any art whatsoever because thats a thing that crashed and burned for no reason

**Comment by Vaygrim** [comment]
All of the original skins got requested and made 'per player' as they joined the server. Only about 6 or 7 of them were done 'ahead of time' in prep for the series. We can handle any new requests the same way, and just handle them one by one as they come in.
