### ISSUE TITLE
(ToDo) BetterQuesting Questiness

### ISSUE THREAD

**Issue by Vaygrim** [GrimCo/CoopLife2#2]
Track BQ Questing progression development here!

**Comment by FoxBotGames** [comment]
From what I can see We can not ONLY change the BQ loot table, BQ lootchests are hooked to the generalized loot table, which means we would be changing basically ALL LootChests
Are we willing to do this?

**Comment by Vaygrim** [comment]
We don't have to go _that far_ with it, we can just try to add stuff to the pre-existing loot tables.
That or just skip the chests, do 'direct rewards' like in Wasted.

**Comment by FoxBotGames** [comment]
Whoop found an editor (in game may I add) that is called Loot Chest Edit (looks enchanted)
Looks like I can create custom groups, each group I am able to control the chance of the items, however the percentages are a little confusing in how it decides from what I input.....

**Comment by FoxBotGames** [comment]
FOR LATER
ADD: Once IRL Day Repeatable quest for one Data Chip of each Type (full)

**Comment by FoxBotGames** [comment]
LORE SUGGESTION
Coop Life, genetically modified creatures escape a GrimCo facility and look for a better life. Coop Life 2 has them progressing to the same level of their creators and focuses in their return to the stars
(MallRat)

**Comment by FoxBotGames** [comment]
LOOT TABLES
Current things: Vanilla stuffs, Wands, Extra Utilities 2 crystals (and Drill core?), tested by me just spamming the loot chests.... I can't find any way to look into what is all actually ON the current loot tables, perhaps someone can show me?

Suggestions to add in:
- Project E: Fuels. Red and Dark Matter (?)
- Advanced Rocketry: Dilithium (Very low), Lithium (Low), Titanium (Low), small Battery, Silicone (nugget and ingot), Linker (because of bug with linker)
- Croporia: foods, Seeds
- Bees?
- Refined Storage: Each type of Processor, Silicone, All 'printed', construction and destruction cores, Machine Casing, Storage Housing, Upgrade (the blank one), cables
(Any other suggestions?)

**Comment by Vaygrim** [comment]
I want to hold off with giving raw EMC sinks like Dark Matter / Red Matter as I want to encourage people to visit other planets to mine that stuff. Also I'd keep the Refined Storage stuff simple as well... processors, silicone, and maybe rarely stuff like the Construction / Destruction Cores yeah.

**Comment by FoxBotGames** [comment]
At that then we dont want to add in the AR stuff, you can only get those from traveling to other planets to mine

**Comment by FoxBotGames** [comment]
Don't trust repeatable quests till BQ Dev says it is resolved or untill BQ Dev is finished rewriting UI

**Comment by FoxBotGames** [comment]
STORY
Once, we were imprisoned by the ones who created us. Only by working together did we manage to escape. We then found ourselves alone in a new world. We gained new knowledge and carved out a place in the world to call "home."
We discovered many new and interesting technologies in our new home, including some new form of alchemy. But now we've reached the limit of what we can learn here.
Now we look to the stars. We've allied with our creators to find a way to leave the place we've called home. It's time to explore new worlds out there. Together, the cosmos is ours!
Courtesy of Heart to paraphrase what I already had.

**Comment by FoxBotGames** [comment]
Add an early game starter quest with Prefab's Starter House as a reward. Maybe collect 16 cobblestone and 16 logs and turn them in.
//To Do
Drop AR Questline
Transfer and Rework Thermal Suit questline from Wasted
TR questline (Low and start Med tier Machines}
Chickens Questline: Machines, Feeding Stations, Hatcheries, 4-6 chicken quests to get them started(?)
Project E: Basics, show how to improve Klein Stars, Power Flower
AA: Basics, Empowering Machine setup(?)

**Comment by FoxBotGames** [comment]
TO FIX:
Data for Klein Star Quest
Name of Atomic Re-constructor Quest
Name of Transmutation Table Quest
Reward for Philosopher's Stone
Redo AA questline

**Comment by FoxBotGames** [comment]
Fininshed
