### ISSUE TITLE
Biomes O' Plenty coral doesn't glow when replanted

### ISSUE THREAD

**Issue by HeartofDragons** [GrimCo/CoopLife2#26]
Just like the title, if you pick up some Biomes O' Plenty coral and put it back down, it no longer glows. Lighting updates don't do anything, either.

**Comment by Vaygrim** [comment]
There's actually only 1 coral that glows (called... "Glowing Coral", heh) the rest of the stuff doesn't actually glow at all. Glowing Coral DOES glow when replanted, have tested on the server.
