### ISSUE TITLE
6-4-18 15:55 latest.log  for client crash?

### ISSUE THREAD

**Issue by popps73x** [GrimCo/CoopLife2#34]
crash happened when I placed an unconfigured powercell with no card in it for the first time next to leadstone fluxducts.

https://www.dropbox.com/s/e8t8wwydryfevcl/latest.log?dl=0

second crash was trying to open the powercell ui.

**Comment by Vaygrim** [comment]
This is related to the versions of mods we're using from McJty. Will be resolved in the next pack update (most likely tomorrow).

**Comment by FoxBotGames** [comment]
Resolved (Tested proof)
