### ISSUE TITLE
Sand Chicken spawns

### ISSUE THREAD

**Issue by CallofParanoia** [GrimCo/CoopLife2#42]
Sand chickens seem to be spawning in Forest type biomes and not in Desert type biomes.
Had it happen in my single player world and PurpleMentat had it happen on stream.
Will add timecodes for VOD as soon as stream finishes.

**Comment by CallofParanoia** [comment]
Search starts at 03:08:30
[PurpleMentat's "Alchemical chickens in space? I'm in. GrimCo's Coop Life 2" VOD](https://www.twitch.tv/videos/272411806?t=03h08m30s)

Sand Chicken found at 03:26:25 in a Chaparral biome

I found my sand chickens in a Forest Hills biome

**Comment by FoxBotGames** [comment]
Chickens Spawn 'locations' are just like bee hives spawn rates. Its based off temperature of a biome not specifically the biome iteself. It may seem weird yes but just imagine a marsh hive in a desert near a little pond.....
