### ISSUE TITLE
Prefab buildings recipies not showing

### ISSUE THREAD

**Issue by Dragonracer73** [GrimCo/CoopLife2#49]
So after some sp testing (Thanx to Multi Mc, which basically amounted to disabling all mods, except Jei and Prefab, then renabling one by one) it appears that the chickens mod is what is causing the recipies to not show in Jei. Not sure why this is happening. I shall promptly go off to the Chickens git and report.

**Comment by Trunks9809** [comment]
Reported to Chickens: setycz/ChickensMod/#131

**Comment by FoxBotGames** [comment]
"Fixed" issue by changing the way the recipe script functions (thanks to the replace all command)
