### ISSUE TITLE
(ToDo) Advanced Rocketry

### ISSUE THREAD

**Issue by Vaygrim** [GrimCo/CoopLife2#6]
Track "Advanced Rocketry" configuring and checking here.

**Comment by FoxBotGames** [comment]
Suggest removing Copper, Tin, and Aluminum ore spawns from the AR configs, I dont think we need more than one of each right? (advRocketry/advancedRocketry.cfg)
(MOST recipes from AR if they need materials are oredict'ed, things like plates and ingots, rods are unique)

**Comment by mallrat208** [comment]
By default AR will override sky rendering in dimensions to show nearby celestial bodies. It's rather neat but there's the potential that it could be bad on performance for someone with Potato PC. We should keep a look at how well performance is in the overworld with the feature enabled and see if turning it off is warranted

**Comment by FoxBotGames** [comment]
AR removed
