### ISSUE TITLE
(ToDo) Missing Mods

### ISSUE THREAD

**Issue by Vaygrim** [GrimCo/CoopLife2#8]
Key mods still missing.
NOTE: This is NOT a place for "Mod Suggestions", that is in another Issue post. If you make such suggestions here, they'll be removed. Thanks!

**Comment by Vaygrim** [comment]
- Lumberjack / Tree Chopper style mod for clearing trees (Fast Leaf Decay included, if possible)
- "Simple Bedding" by Mallrat208

**Comment by Vaygrim** [comment]
Mod that allows "Right Click to Harvest crops"

**Comment by Vaygrim** [comment]
Vending Machines:
https://www.curseforge.com/minecraft/mc-mods/good-ol-currency

Survival Systems (by Mallrat208)
Tropicraft (Dedicated Planet)

**Comment by FoxBotGames** [comment]
Morpheus
Because yah know.... ITS MISSING FOR SOME REASON

**Comment by Vaygrim** [comment]
Considering the mod list as 'closed', currently. Don't need anything large or feature-adding at this late point in the release schedule.
