### ISSUE TITLE
MOD SUGGESTIONS

### ISSUE THREAD

**Issue by Vaygrim** [GrimCo/CoopLife2#9]
Think the pack is missing some key mod that you like? Make your suggestion here.

NOTE: For a suggestion to even be _considered_ you need to include a statement as to **why** you think it should be included in the pack. Posts with nothing but a mod name in it will be ignored and removed.

**Comment by mallrat208** [comment]
We probably want Hatchery, it was the mod that added in a lot of the automation stuff for the Chickens mod
https://minecraft.curseforge.com/projects/hatchery

Things like the Nesting Pen, Animal Net, Fertilizer, and Chicken Poop Generator Thing

**Comment by popps73x** [comment]
found this mod which adds procedurally generated Chisel textures for Forestry wood and Binnie's woods(along with a number of other mods).  https://www.curseforge.com/minecraft/mc-mods/unlimited-chisel-works  it does have an issue of creating a lot of block ID's but in a smaller pack should be less of an issue.  there is also an extension for it for the rest of the botany blocks from Binnie's such as pigmented glass and ceramics. I would personally be more interested in the first but if there is room for both that would be great.  https://www.curseforge.com/minecraft/mc-mods/unlimited-chisel-works-botany
